### ISSUE TITLE
 Split ForceTorqueEstimator into two entities

### ISSUE THREAD

**Issue by andreadelprete** [stack-of-tasks/sot-torque-control#12]
Currently the entity ForceTorqueEstimator computes:
- joint velocities and accelerations (using polynomial filters)
- joint torques and contact wrenches

Since the computation of joint velocities and accelerations is independent of the second operation we should split this entity into two. This makes especially sense considering that for the new robot (Pyrene) we will not need to estimate the joint torques using the robot dynamic model as we do now for HRP-2, but we'll still need to estimate the joint velocities (and maybe also the accelerations).

**Comment by proyan** [comment]
The position, velocity and acceleration signal outputs are filtered out values from the base6d_encoder signal. Currently the internal signal torques_wrenches in force-torque-estimator is using these filtered output of position, velocity and acceleration signals. 

I have created a separate entity (vel-acc-estimator) which outputs the pos-vel-acc signals now. I see two ways forward:

- Take these filtered signals out from the vel-acc-estimator and plug them back in force-torque-estimator.
- Re-filter the signals again in the force-torque-estimator

I prefer and am implementing the second option, as it would maintain the independence of the two estimators. Could you please let me know if you disagree?
