### ISSUE TITLE
 Read joint limits and sensor positions from urdf file rather than from hrp2_common.hh

### ISSUE THREAD

**Issue by andreadelprete** [stack-of-tasks/sot-torque-control#14]
A lot of robot-related information is currently read from the header file hrp2-common.hh, such as joint limits and position of IMU and force/torque sensors in local reference frame. This information could be actually read from the urdf file, so that it would be easier to use the code with a different robot.

**Comment by andreadelprete** [comment]
This issue is kind-of addressed by the work of Olivier Stasse in its fork of sot-torque-control, which is currently under test, but will be soon merged in this repository

**Comment by olivier-stasse** [comment]
Fixed #14 by commit c3ca99841e67e00480c40e2b4fcded00aade0dd1
