### ISSUE TITLE
Simple humanoid description as an optional dependency

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/sot-torque-control#46]
It's nice to use a simple humanoid robot for the unit testing and benchmarking. However, the simple-humanoid-description packages should be an optional dependency, this is required only when we're interesting in compiling the unit-test.

@olivier-stasse What do you think about it?

**Comment by olivier-stasse** [comment]
The simple_humanoid_description package can be easily installed through robotpkg.
I am not sure this is a fundamental issue here.
