### ISSUE TITLE
Add link to simple_humanoid_description

### ISSUE THREAD

**Issue by jviereck** [stack-of-tasks/sot-torque-control#53]
The project requires the package `simple_humanoid_description` to build but it is not clear where this project is located. A link to the project should be provided.

**Comment by andreadelprete** [comment]
Maybe this dependency was intended to be optional because on [this line](https://github.com/stack-of-tasks/sot-torque-control/blob/master/CMakeLists.txt#L213) it says 
```
 IF(SIMPLE_HUMANOID_DESCRIPTION_FOUND)
```
Probably @olivier-stasse can answer this

**Comment by olivier-stasse** [comment]
@jviereck 
https://github.com/laas/simple_humanoid_description
or (easier)
```
apt-get install robotpkg-simple-humanoid-description
```
All the packages we are using are either available through Ubuntu canonical ppa-repository or in robotpkg.

Thanks for your contribution.
